# Generated by Django 6.1 on 2026-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsupportassitant',
            name='skills',
            field=models.ManyToManyField(related_name='lsas', to='allinone.skills'),
        ),
        migrations.AddIndex(
            model_name='learningsupportassitant',
            index=models.Index(fields=['is_active'], name='allinone_le_is_acti_a2f274_idx'),
        ),
    ]
